---
- name: setup of jenkins server and required s/w's
  hosts: jenkinsserver
  tasks:
   - name: install required s/w's
     apt:
      name: "{{item.a}}" 
      state: present
      update_cache: "{{item.b}}" 
     with_items:
      - {a: openjdk-8-jdk,b: yes} 
      - {a: git,b: no}
      - {a: maven,b: no} 

   - name: download jenkins.war
     get_url:
      url: https://get.jenkins.io/war-stable/2.289.2/jenkins.war
      dest: /tmp 
      
- name: install tomcat9 and tomcat-admin
  hosts: servers
  tasks:
   - name: install tomcat9
     apt:
      name: "{{item.a}}"
      state: present
      update_cache: "{{item.b}}"
     with_items:
      - {a: tomcat9,b: yes} 
      - {a: tomcat9-admin,b: no}  
   
   - name: copy the tomcat-user.xml
     copy:
      src: tomcat-user.xml
      dest: /etc/tomcat9
     
     notify: restart tomcat9
  handlers:
   - name: restart tomcat9    
     service: 
      name: tomcat9
      state: restarted
...      
      


