---
- name: check if a folder called d1 is present if not create a file called d1
  hosts: all
  tasks: 
   - name: check for d1 directory
     stat: 
      path: /home/ubuntu/d1
     register: a
   - name: display output of above module
     debug:
      var: a
   - name: create file d1 if d1 directory d1 is not present
     file:
      name: /home/ubuntu/d1
      state: touch
     when: a.stat.exists == false 

